"""link stock and user tables

Revision ID: 9e531908029a
Revises: f08e4b9a284d
Create Date: 2022-04-14 09:48:27.286033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e531908029a'
down_revision = 'f08e4b9a284d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_price_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('position_value', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stocks_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stocks_user_id_users'), type_='foreignkey')
        batch_op.drop_column('position_value')
        batch_op.drop_column('current_price_date')
        batch_op.drop_column('current_price')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
