"""empty message

Revision ID: e91953ecc365
Revises: 9e531908029a
Create Date: 2022-04-14 14:16:49.306294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91953ecc365'
down_revision = '9e531908029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchstocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('current_share_price', sa.Integer(), nullable=True),
    sa.Column('current_share_price_date', sa.DateTime(), nullable=True),
    sa.Column('fiftytwo_week_low', sa.Integer(), nullable=True),
    sa.Column('fiftytwo_week_high', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.String(length=255), nullable=True),
    sa.Column('dividend_per_share', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Integer(), nullable=True),
    sa.Column('peg_ratio', sa.Integer(), nullable=True),
    sa.Column('profit_margin', sa.Integer(), nullable=True),
    sa.Column('beta', sa.Integer(), nullable=True),
    sa.Column('price_to_book_ratio', sa.Integer(), nullable=True),
    sa.Column('stock_data_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchstocks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchstocks'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    op.drop_table('watchstocks')
    # ### end Alembic commands ###
