name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: azure/docker-login@v1
        with:          
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          login-server: huybtregistry.azurecr.io
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: huybtregistry.azurecr.io/webapp:latest
          file: ./Dockerfile
          
      - name: Deploy app 
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'webapp-huybt'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'huybtregistry.azurecr.io/webapp:latest'
