name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Log in to azure container registry
        uses: azure/docker-login@v1
        with:  
          login-server: tgwebapp.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
                   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: |
          docker build . -t tgwebapp.azurecr.io/webapp:latest
          docker push tgwebapp.azurecr.io/webapp:latest
        
      - name: Deploy app to webbapp
        uses: azure/webapps-deploy@v2
        with:
            app-name: itawebapp
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: tgwebapp.azurecr.io/webapp:latest
